#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-gradle-scoverage
Version  : 2.5.0
Release  : 1
URL      : https://github.com/scoverage/gradle-scoverage/archive/2.5.0.tar.gz
Source0  : https://github.com/scoverage/gradle-scoverage/archive/2.5.0.tar.gz
Source1  : https://repo.gradle.org/gradle/libs-releases/org/scoverage/gradle-scoverage/2.5.0/gradle-scoverage-2.5.0.jar
Source2  : https://repo.gradle.org/gradle/libs-releases/org/scoverage/gradle-scoverage/2.5.0/gradle-scoverage-2.5.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-gradle-scoverage-data = %{version}-%{release}
Requires: mvn-gradle-scoverage-license = %{version}-%{release}
BuildRequires : buildreq-mvn
BuildRequires : gradle

%description
[![Build Status](https://travis-ci.org/scoverage/gradle-scoverage.png?branch=master)](https://travis-ci.org/scoverage/gradle-scoverage)

%package data
Summary: data components for the mvn-gradle-scoverage package.
Group: Data

%description data
data components for the mvn-gradle-scoverage package.


%package license
Summary: license components for the mvn-gradle-scoverage package.
Group: Default

%description license
license components for the mvn-gradle-scoverage package.


%prep
%setup -q -n gradle-scoverage-2.5.0

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-gradle-scoverage
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/mvn-gradle-scoverage/LICENSE.txt
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/scoverage/gradle-scoverage/2.5.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/scoverage/gradle-scoverage/2.5.0/gradle-scoverage-2.5.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/scoverage/gradle-scoverage/2.5.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/scoverage/gradle-scoverage/2.5.0/gradle-scoverage-2.5.0.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/scoverage/gradle-scoverage/2.5.0/gradle-scoverage-2.5.0.jar
/usr/share/java/.m2/repository/org/scoverage/gradle-scoverage/2.5.0/gradle-scoverage-2.5.0.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-gradle-scoverage/LICENSE.txt
